name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Env var
      run: env
    - name: Install Criterion
      run: |
        sudo add-apt-repository ppa:snaipewastaken/ppa
        sudo apt-get update
        sudo apt-get install criterion-dev
    - name: Build as lib
      run: make
    - name: Run unit tests
      run: make tests_run
